CREATE DATABASE IF NOT EXISTS aito;
USE aito;

CREATE TABLE IF NOT EXISTS gaestebuch (
	EintragID INT AUTO_INCREMENT,
	Ersteller VARCHAR,
	Eintrag VARCHAR,
	Erstelldatum TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (EintragID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;